encoding: UTF-8
lang: vi
timezone: Asia/Ho_Chi_Minh
title: NetTV
email: lactran.vh@gmail.com
description: NetTV Blog
author: Lạc Trần
baseurl: ''
url: vh365.github.io
twitter_username: null
github_username: vh365
facebook_username: null
instagram_username: null
linkedin_username: null
google_analytics: UA-XXXXXXXXX-X
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
compress_html:
  comments:
    - <!--
    - '-->'
  blanklines: false
sass:
  sass_dir: _sass
  style: ':compressed'
permalink: '/:categories/:title'

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - cmd.exe
